/*
 * MenuPane.java
 *
 * Created on 17 October 2007, 07:31
 */

package sydneyengine.ui;

import javax.swing.JInternalFrame;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;

import sydneyengine.shooter.ViewPane;
/**
 *
 * @author  Leeder
 */
public class MenuPane extends javax.swing.JPanel {
	ViewPane v;
	JInternalFrame f;
	/** Creates new form MenuPane */
	public MenuPane(final ViewPane v, final JInternalFrame f) {
		initComponents();
		this.v = v;
		this.f = f;
		
		// To give focus to the viewPane once this menu is destroyed
		f.addInternalFrameListener(new InternalFrameAdapter(){
			@Override
			public void internalFrameClosed(InternalFrameEvent e){
				v.requestFocus();
			}
		});
		
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionsButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        quitButton = new javax.swing.JButton();
        changeTeamButton = new javax.swing.JButton();
        returnToGameButton = new javax.swing.JButton();
        playerOptions = new javax.swing.JButton();
        returnToGameButton1 = new javax.swing.JButton();

        optionsButton.setText("Perfomance options"); // NOI18N
        optionsButton.setToolTipText("Geeky stuff");
        optionsButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                options(evt);
                jButton1createGame(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 36));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Defiance"); // NOI18N

        quitButton.setText("Quit game"); // NOI18N
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                quit(evt);
            }
        });

        changeTeamButton.setText("Teams and scores"); // NOI18N
        changeTeamButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeTeam(evt);
            }
        });

        returnToGameButton.setText("Return to game"); // NOI18N
        returnToGameButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToGame(evt);
            }
        });

        playerOptions.setText("Help!"); // NOI18N
        playerOptions.setToolTipText("Tells you what to do and describes what the keys are.");
        playerOptions.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerOptionsreturnToGame(evt);
                playerOptions(evt);
            }
        });

        returnToGameButton1.setText("Switch look and feel!"); // NOI18N
        returnToGameButton1.setActionCommand("Switch look and feel!");
        returnToGameButton1.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchLookAndFeel(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 436, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(changeTeamButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 436, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(quitButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 436, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(optionsButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 436, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(playerOptions, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 436, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(returnToGameButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 436, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(returnToGameButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 436, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(changeTeamButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(quitButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(optionsButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(playerOptions, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(returnToGameButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(returnToGameButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void playerOptions(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerOptions
		//System.out.println(this.getClass().getSimpleName()+": ");
		v.getGameFrame().doHelpMenu(v);
		f.dispose();
	}//GEN-LAST:event_playerOptions

	private void playerOptionsreturnToGame(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerOptionsreturnToGame
// TODO add your handling code here:
	}//GEN-LAST:event_playerOptionsreturnToGame

	private void returnToGame(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToGame
		v.getGameFrame().getDesktopPane().remove(f);
		f.dispose();
		v.requestFocus();
	}//GEN-LAST:event_returnToGame

	private void changeTeam(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeTeam
		//System.out.println(this.getClass().getSimpleName()+": ");
		v.getGameFrame().doTeamsAndScoresMenu(v);
		f.dispose();
	}//GEN-LAST:event_changeTeam

	private void jButton1createGame(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1createGame
// TODO add your handling code here:
	}//GEN-LAST:event_jButton1createGame

	private void quit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quit
		v.getGameFrame().doStart();
	}//GEN-LAST:event_quit

	private void options(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_options
		v.getGameFrame().doOptionsMenu(v);
		f.dispose();
	}//GEN-LAST:event_options

	private void switchLookAndFeel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchLookAndFeel
		v.getGameFrame().doLookAndFeelMenu(v);
		f.dispose();
}//GEN-LAST:event_switchLookAndFeel
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeTeamButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton optionsButton;
    private javax.swing.JButton playerOptions;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton returnToGameButton;
    private javax.swing.JButton returnToGameButton1;
    // End of variables declaration//GEN-END:variables
	
}
