/*
 * ServerStatisticsPane.java
 *
 * Created on 27 January 2008, 15:36
 */

package sydneyengine.ui;

import javax.swing.JDialog;

import sydneyengine.lobby.LobbyInfo;
/**
 *
 * @author  woodwardk
 */
public class ServerStatisticsPane extends javax.swing.JPanel {
	JDialog dialog;
	/** Creates new form ServerStatisticsPane */
	public ServerStatisticsPane(JDialog dialog, LobbyInfo lobbyInfo) {
		this.dialog = dialog;
		initComponents();
		playersOnlineNowLabel.setText(""+lobbyInfo.getNumPlayersConnected());
		mostPlayersOnlineLabel.setText(""+lobbyInfo.getMostPlayersOnline());
		totalNumPlayersConnectedLabel.setText(""+lobbyInfo.getTotalNumPlayersConnected());
		dateOfServerBirthLabel.setText(""+lobbyInfo.getDateOfServerBirth());
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mostPlayersOnlineLabel = new javax.swing.JLabel();
        totalNumPlayersConnectedLabel = new javax.swing.JLabel();
        dateOfServerBirthLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        playersOnlineNowLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();

        jLabel1.setText("Most players online at once:");

        jLabel2.setText("Total number of players who have connected:");

        jLabel3.setText("Date that current server was started:");

        mostPlayersOnlineLabel.setText("jLabel4");

        totalNumPlayersConnectedLabel.setText("jLabel4");

        dateOfServerBirthLabel.setText("jLabel4");

        jLabel4.setText("Players online now:");

        playersOnlineNowLabel.setText("jLabel4");

        jLabel5.setText("Please note that these stats don't refresh automatically,");

        jLabel6.setText("so you'll have to close and re-open this dialog.");

        exitButton.setText("OK");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 117, Short.MAX_VALUE)
                        .add(playersOnlineNowLabel))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 117, Short.MAX_VALUE)
                        .add(mostPlayersOnlineLabel))
                    .add(layout.createSequentialGroup()
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 117, Short.MAX_VALUE)
                        .add(totalNumPlayersConnectedLabel))
                    .add(layout.createSequentialGroup()
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 117, Short.MAX_VALUE)
                        .add(dateOfServerBirthLabel))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                    .add(exitButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(playersOnlineNowLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(mostPlayersOnlineLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(totalNumPlayersConnectedLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(dateOfServerBirthLabel))
                .add(18, 18, 18)
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 28, Short.MAX_VALUE)
                .add(exitButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

	private void exitButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton
		dialog.dispose();
	}//GEN-LAST:event_exitButton

	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel dateOfServerBirthLabel;
    protected javax.swing.JButton exitButton;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel2;
    protected javax.swing.JLabel jLabel3;
    protected javax.swing.JLabel jLabel4;
    protected javax.swing.JLabel jLabel5;
    protected javax.swing.JLabel jLabel6;
    protected javax.swing.JLabel mostPlayersOnlineLabel;
    protected javax.swing.JLabel playersOnlineNowLabel;
    protected javax.swing.JLabel totalNumPlayersConnectedLabel;
    // End of variables declaration//GEN-END:variables
	
}
